### PR TITLE
fix: child back button dispatcher

### LINKED ISSUE #5: [Bug] BackButtonDispatcher priority
`DuckShellState` has a typo that prevents it from correctly calling `takePriority` on its child back button dispatchers.
The function is missing the parenthese to actually execute the call.

The issue occurs [here](
https://github.com/collectiveuk/packages/blob/2abeb5a15c8508b9c64676ef2b27a43cd71edd32/flutter/packages/duck_router/lib/src/shell.dart#L106).

### PR DESCRIPTION
**Pull request by JaspervanRiet**
## Description

This PR fixes an issue where we were not calling the child back button dispatcher to take priority. It was hard to replicate, but the second test this PR contributed fails for the previous code after popping twice.

## Related Issues

Closes #5

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

### CODE REVIEW

File: flutter/packages/duck_router/test/src/duck_router_test.dart [hunk 1]
```diff
@@ -409,6 +409,73 @@ void main() {
...
+      expect(find.byType(HomeScreen), findsOneWidget);
+
+      // Simulate a back button press
+      await tester.binding.handlePopRoute();
+      await tester.pumpAndSettle();
+
+      // Check if we're still on the HomeScreen (we shouldn't be)
+      expect(find.byType(HomeScreen), findsNothing);
+
+      // We should have returned to the RootLocation, but we haven't
```
Comment (lindsay-cb) [inline flutter/packages/duck_router/test/src/duck_router_test.dart:434]: I find this comment + assertion confusing. Where should we be, where are we?

Comment (JaspervanRiet) [reply flutter/packages/duck_router/test/src/duck_router_test.dart]: Let me know if it's clearer now

**Review by lindsay-cb — APPROVED** [review]
🎉 lgtm
